name: Enable Automerge
on:
  pull_request_target:
    branches:
    - mainn

jobs:
  enable-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ github.token }}
